### PR TITLE
Unify deployment chaos by using the location independent build

### LINKED ISSUE #300: Delete other docker images, trim down env files
Once the location independent image has been tested for a bit, we can probably convert the other two deployments to use the same image, cutting down action runtime and complexity.

This issue is just a small reminder that we likely want to look at this in the nearish future.

### PR DESCRIPTION
**Pull request by I-Al-Istannen**
## Motivation
Currently quite a few different docker and frontend versions are floating around but only *one* is really needed.  
In #310 the Aaaaaaah instance deployment was moved to the location-independent docker image and now we could migrate the Lean deployment to the location-independent image too.

Additionally, we can use this to consolidate the docker tags and images a bit and standardize on `latest` for what previously was `build-location-independent`, removing the current `main` (which is the lean-only deployment).

## Changes in this PR
- The kit/aaaaaaah frontend env files were removed and the production env file now points to the location independent image
- The aaaaaaah deploy scripts were deleted
- The `build-kit-frontend` and `push-kit` workflow steps were deleted
- The `location-independent-image` tag was renamed to `latest`. It is the main artifact now and should follow docker conventions a bit better

## Required setup adjustments
- **The Lean deployment** currently uses the `main` image which will no longer exist. *Ideally*, no change besides using the `latest` tag is required. I wouldn't exactly bet too much money on that though, so some monitoring and maybe a quick db copy would be a good idea.
- **The Compprak deployment** needs to change the image name from `build-location-independent` to `latest`
- **The Aaaaaaah deployment** needs to change the image name from `build-location-independent` to `latest`

## Merging process
If you both made the necessary changes on your side, this PR can be merged and everything might be in working order :) I think you can make the changes whenever you want, independently, and if both are done this can be merged. The existing instances should continue to run with these changes, as long as you do not manually trigger a re-deployment.  
This PR merge can then act as the first test of the new deployment. 

Closes #300.

### CODE REVIEW

**Comment by sgraf812** [comment]
I haven't reviewed the changes to the Dockerfile in detail, nor did I understand it before. But it seems to shuffle things around in a good way, so I'm going to merge this.

With the other .env-files gone, what is the way to set up a development instance? I suppose that https://github.com/IPDSnelting/velcom/blob/main/docs/install_manual.md#frontend is still up to date on that matter, right?

**Comment by I-Al-Istannen** [comment]
> With the other .env-files gone, what is the way to set up a development instance?

The `.development` file is still there, only the KIT and Aaaaaaah files are gone. I'll have a look at the manual install afterwards but nothing should have changed.

I'll also fix the oversight that currently caused the CI to fail in a minute...

**Comment by I-Al-Istannen** [comment]
Okay, I was too slow for @Kha. Thank you :)

**Comment by I-Al-Istannen** [comment]
Things seem to work now, thank you both so much for your patience and impromptu fixes for my image name screwup :)

This was a ride, I didn't quite expect the name to be wrong, I must have changed that accidentally when cleaning up the tags...

**Pull request merged**
