### PR TITLE
GitHub Bot

### PR DESCRIPTION
**Pull request by Garmelon**
This PR adds GitHub bot functionality to VelCom. To enable it for a repo, go to its detail page as admin and follow the instructions there. To trigger a benchmark of a PR, add a comment containing only `!bench` on that PR. Only accounts with write access to the repo can use this command, the bot ignores everyone else. Tasks triggered this way have the same queue priority as uploaded tar files - below one-upped tasks but above newly detected commits.

**Required manual changes:**
This PR adds the `frontendUrl` option to the config file (documented in the [example config][1]). It also includes a DB migration, in case you want to make a backup first. Feel free to fast-forward this PR yourself whenever you're ready.

**Details:**
- VelCom assumes that the token is valid. If it isn't, the repo may not be updated correctly.
- If the bot is enabled for a repo, VelCom searches for new commands at the same time as new commits. This search can thus be triggered manually via the "Refetch all repos" button on the queue page.
- Once a comment is detected as a command, the bot reacts with a :+1: before doing anything else with the command.
- The bot will benchmark the PR's commit at the time it detected the command.
- If multiple commands are made for the same PR and commit, the bot may only respond with a single message, although it will still react with :+1: to every single command.
- If one or more runs already exist for a given PR and commit, the bot will post the newest run and *not* re-benchmark. To re-benchmark a commit, you need to use the re-benchmark button in the VelCom UI while logged in as an admin. However, keep in mind that the bot's old link will still point to the old run. To make it post the new link after re-benchmarking, just issue another `!bench` command.

We haven't tested this a lot, especially not at a larger scale, so if you notice any buggy behaviour, let us know.

[1]: https://github.com/IPDSnelting/velcom/blob/04afde90f33408796f1a028fee6257546b492f31/backend/backend/src/main/resources/example_config.yml#L55-L62

### CODE REVIEW

**Comment by Kha** [comment]
Should the descriptions tell you to maybe create a separate bot account for the token in case you don't like to congratulate yourself? :grin: 
image

**Comment by I-Al-Istannen** [comment]
That sounds like a plan ;)
It shouldn't always link to VelCom as well, that seems to have slipped through. I will open a draft PR for accumulating those bugs if you don't mind.

**Comment by Kha** [comment]
:tada: :tada: :tada: https://github.com/leanprover/lean4/pull/521#issuecomment-858368293

**Comment by Kha** [comment]
Mmh, a second `!bench` didn't trigger :( . I did change the PAT to the bot in between, see response to the first command. I don't see anything in the logs. Any clues?

**Comment by Kha** [comment]
I figured it out, the token needs push (!) access to check permissions. That should be mentioned in the new text, and such failures should also always be logged (i.e. with level > debug).

**Comment by I-Al-Istannen** [comment]
Uff, that's a new one. I can't seem to find *any* detailed documentation on Github's permission levels, so I will probably add that to the instructions without a source... It does sound quite unfortunate that you need to grant the bot push access, that's a bit more responsibility than I'd expect it to require.

Based on the comments in the issues, showing the difference in sigmas might also be useful for the comparison? If you can think of any usability improvements there, feel free to open an issue :)

**Comment by Kha** [comment]
Fwiw, this was the response from GitHub with a manual request:
```
{
  "message": "Must have push access to view collaborator permission.",
  "documentation_url": "https://docs.github.com/rest/reference/repos#get-repository-permissions-for-a-user"
}```

**Comment by I-Al-Istannen** [comment]
Thank you for that :) I don't see any mention on the documentation page, but that message is quite clear at least.

Apparently users will have to trust us that VelCom doesn't randomly push stellar new commits to their repo. That's annoying, but probably not too bad.

**Pull request merged**
